Assets/Scenes/Gameflow/InGame.unity
Assets/featuer_docSO/Data(test).meta
Assets/featuer_docSO/Data(test)/bug.asset
Assets/featuer_docSO/Data(test)/bug.asset.meta
Assets/featuer_docSO/Data(test)/file.asset
Assets/featuer_docSO/Data(test)/file.asset.meta
Assets/featuer_docSO/Data(test)/folder.asset
Assets/featuer_docSO/Data(test)/folder.asset.meta
Assets/featuer_docSO/Data(test)/hand.asset
Assets/featuer_docSO/Data(test)/hand.asset.meta
Assets/featuer_docSO/Data(test)/postit.asset
Assets/featuer_docSO/Data(test)/postit.asset.meta
Assets/featuer_docSO/Document/DocumentController.cs
Assets/featuer_docSO/Document/DocumentData.cs
Assets/featuer_docSO/Document/DocumentPool.cs
Assets/featuer_docSO/Document/ObstacleController.cs
Assets/featuer_docSO/Document/ObstacleData.cs

난이도 상승에 비례한 장애물 처리 난이도 변화 구현
---
about: PR 템플릿
labels: review
assignees: ""
---
런타임으로 서류, 장애물 so를 생성하던 방식에서 미리 생성후 뽑아오는 방식으로 변경
난이도 체계 변경
- 날벌레, 포스트잇은 day수가 5를 넘길때마다 하나씩 추가
- 손, 서류철, 폴더는 day수가 5를 넘길때마다 터치 횟수를 하나씩 추가
Closes #7

[Feat] 난이도 상승에 비례한 장애물 처리 난이도 변화 구현

---

Assets/Script/Managers/InGameController.cs
Assets/Script/UI/PopupUI/PauseUIController.cs

---
about: PR 템플릿
labels: review
assignees: ""
---
- [Feat] 재시작 버튼 기능 구현
Closes #17

[Feat] 재시작 버튼 기능 구현

---

Assets/featuer_docSO/Document/DocumentController.cs

변수 이름: _isClickable, true시 클릭 가능, false시 클릭 불가능
---
about: PR 템플릿
labels: review
assignees: ""
---
DocumentController에 버튼 연타 방지용 bool값 추가했습니다.
변수이름은 _isClickable이고,
클릭이 허용되는 시점이면 true, 
클릭을 하면 안되는 시점이면 false,로 bool값이 바뀌게 로직을 짰습니다

[Docs] DocumentController에 버튼 연타 방지용 bool값 추가

---

Assets/Prefab/UI/InGame/FeverUI.prefab
Assets/Prefab/UI/InGame/FeverUI.prefab.meta
Assets/Scenes/Gameflow/InGame.unity
Assets/Scenes/Gameflow/Raise.unity
Assets/Script/Managers/GameManager.cs
Assets/Script/Managers/InGameController.cs
Assets/Script/UI/InGameUI/FeverUIController.cs
Assets/Script/UI/InGameUI/FeverUIController.cs.meta
Assets/Script/UI/InGameUI/InteractionUIController.cs
Assets/Script/UI/InGameUIController.cs
Assets/Scripts/ButtonController.cs
Assets/Scripts/Classification.cs
Assets/featuer_docSO/Document/DocumentController.cs

Fever상태 진입 시 문서 장애물 안나오는것을 제외하고 구현해 놨습니다. 추후 문서관련 에러가 수정되면 추가할 예정입니다. classification싱글톤 제거했습니다. GameManager.instance.GetClassification()을 사용해주세요
---
about: PR 템플릿
labels: review
assignees: ""
---
[Fever상태 진입 시 문서 장애물 안나오는것을 제외하고 구현해 놨습니다. 추후 문서관련 에러가 수정되면 추가할 예정입니다. classification싱글톤 제거했습니다. GameManager.instance.GetClassification()을 사용해주세요]

Fever 게이지 추가 및 classification 싱글톤제거

---

Assets/Script/UI/InGameUI/InteractionUIController.cs

---
about: PR 템플릿
labels: review
assignees: ""
---
- [Fix] 서류 처리 버튼이 무딜레이 연타되지 않도록 수정.
Closes #44

[Fix] 서류 처리 버튼이 무딜레이 연타되지 않도록 수정.

---

Assets/Prefab/UI/Popup/ResultUI.prefab
Assets/Scenes/Gameflow/Raise.unity
Assets/Script/UI/PopupUI/ResultUIController.cs

- 게임 결과 표시 효과 제작 (점수가 순차적으로 0부터 오르도록)
- 만약 결과값이 신기록이라면 추가 효과 제작 (New Record!! 글자가 생성되며 계속 깜빡거리도록)
---
about: PR 템플릿
labels: review
assignees: ""
---
- 게임 결과 표시 효과 제작 (점수가 순차적으로 0부터 오르도록)
- 만약 결과값이 신기록이라면 추가 효과 제작 (New Record!! 글자가 생성되며 계속 깜빡거리도록)
Closes #37 

[Feat] Add Result Effect

---

Assets/Data/ScriptableObject/VFXDatas/ObsTouchVfx.asset

---
about: PR 템플릿
labels: review
assignees: ""
---

[Fix]vfx프리팹참조문제수정

---

Assets/Prefab/Game/DocumentController.prefab
Assets/Prefab/UI/InGameUICanvas.prefab

---
about: PR 템플릿
labels: review
assignees: ""
---
- [Resource] 범위 밖에 표시된 UI 가려지도록 마스킹처리

[Resource] 범위 밖에 표시된 UI 가려지도록 마스킹처리

---

Assets/Prefab/UI/InGame/WaitThreeSecondsUI.prefab
Assets/Prefab/UI/InGame/WaitThreeSecondsUI.prefab.meta
Assets/Scenes/Gameflow/InGame.unity
Assets/Scenes/Gameflow/Raise.unity
Assets/Script/Managers/InGameController.cs
Assets/Script/UI/InGameUI/WaitThreeSecondsUI.cs
Assets/Script/UI/InGameUI/WaitThreeSecondsUI.cs.meta
Assets/Script/UI/InGameUIController.cs

3,2,1 Start 구현
---
about: PR 템플릿
labels: review
assignees: ""
---
게임 시작 시 3, 2, 1 Start 출력 후 게임시작

3,2,1 Start 구현

---

Assets/Prefab/UI/InGame/ClassificationUI.prefab
Assets/Script/UI/InGameUI/ClassificationUIController.cs

[Feat]시간증감이펙트추가
---
about: PR 템플릿
labels: review
assignees: ""
---
ClassificationUIController.cs 수정
Closes #65 

[Feat]시간증감이펙트추가

---

Assets/Prefab/UI/Popup/ResultUI.prefab
Assets/Resource/Sprite/Button/Button_Leave.png.meta
Assets/Script/UI/PopupUI/ResultUIController.cs

- 결과창 Sprite 적용
- NewRecord시, Sprite 적용 및 그에 맞춰서 효과 변경
---
about: PR 템플릿
labels: review
assignees: ""
---
- 결과창 Sprite 적용
- NewRecord시, Sprite 적용 및 그에 맞춰서 효과 변경
Closes #61 

[Feat] 결과창 UI Sprite 적용 및 NewRecord 효과 수정

---

Assets/Script/UI/InGameUI/WaitThreeSecondsUI.cs

setActive 추가
---
about: PR 템플릿
labels: review
assignees: ""
---
setActive 추가

setActive 추가

---

Assets/Script/Managers/InGameController.cs
Assets/Scripts/Classification.cs

FeverValue 배율 변경
---
about: PR 템플릿
labels: review
assignees: ""
---
FeverValue 배율 변경

FeverValue 배율 변경

---

Assets/featuer_docSO/Document/DocumentController.cs

결과창에서장애물터치되던버그수정
---
about: PR 템플릿
labels: review
assignees: ""
---

[Fix]결과창에서장애물터치되던버그수정

---

Assets/featuer_docSO/Document/ObstacleClearEffect.cs
Assets/featuer_docSO/Document/ObstacleController.cs

---
about: PR 템플릿
labels: review
assignees: ""
---
- [Feat] 연속처리대상 터치 시 진동모션, 파리 대기모션 추가
Closes #46

[Feat] 연속처리대상 터치 시 진동모션, 파리 대기모션 추가

---

Assets/Resource/Sprite/Button/Buton_Next.png.meta
Assets/Resource/Sprite/Button/Button_Leave.png.meta
Assets/Resource/Sprite/Button/Button_Resume.png.meta
Assets/Resource/Sprite/Button/Button_Retry.png.meta
Assets/Resource/Sprite/Button/Button_title.png.meta
Assets/Resource/Sprite/Button/Main_How.png.meta
Assets/Resource/Sprite/Button/Main_Start.png.meta
Assets/Resource/Sprite/Button/Sound_mute.png.meta

---
about: PR 템플릿
labels: review
assignees: ""
---
- [Resource] 버튼 UI 이미지 슬라이스처리

[Resource] 버튼 UI 이미지 슬라이스처리

---

Assets/AddressableAssetsData/AssetGroups/Default Local Group.asset
Assets/Prefab/UI/Popup/PauseUI.prefab
Assets/Prefab/UI/PopupUICanvas.prefab
Assets/Script/Common/Addresses.cs
Assets/Script/Managers/AudioManager.cs
Assets/Script/UI/PopupUI/PauseUIController.cs
Assets/Script/UI/PopupUIController.cs
Assets/featuer_docSO/Document/ObstacleClearEffect.cs

---
about: PR 템플릿
labels: review
assignees: ""
---
- [Resource] PauseUI 리소스 적용 및 기능 보강
Closes #80

[Resource] PauseUI 리소스 적용 및 기능 보강

---

Assets/Prefab/UI/Title/MainBackGroundUI.prefab
Assets/Prefab/UI/Title/MainBackGroundUI.prefab.meta
Assets/Prefab/UI/Title/MainMenuUI.prefab
Assets/Prefab/UI/Title/SubMenuUI.prefab
Assets/Scenes/Gameflow/Raise.unity
Assets/Script/UI/TitleUI/SubMenuUIController.cs

---
about: PR 템플릿
labels: review
assignees: ""
---
타이틀 UI 리소스 적용

Feature/콤보 피버 점수 및 배율 기능 구현

---

Assets/@KYJ/TimeController.cs

---
about: PR 템플릿
labels: review
assignees: ""
---
TimeController.cs수정

[Fix]day가넘어갈때타이머가초기화되는문제수정

---

Assets/Scenes/Gameflow/Raise.unity

---
about: PR 템플릿
labels: review
assignees: ""
---
Tilte LOGOUI 추가해서 수정했습니다

Title 로고UI 추가

---

Assets/@KYJ/TimeController.cs
Assets/Scripts/Classification.cs

---
about: PR 템플릿
labels: review
assignees: ""
---
Classification.cs, TimeController.cs 수정

[fix]시간ui갱신및장애물페널티버그수정

---

Assets/Script/UI/InGameUI/ClassificationUIController.cs

---
about: PR 템플릿
labels: review
assignees: ""
---
서류 분류 잔상 버그 해결

서류분류 이펙트 잔상 버그 해결

---

Assets/Script/UI/PopupUI/ResultUIController.cs

- Init 할 때 SetActive(false) 처리하도록 수정
---
about: PR 템플릿
labels: review
assignees: ""
---
- Init 할 때 SetActive(false) 처리하도록 수정
Closes #95 

[Fix] 결과창에서 New Record Image 남아있는 버그

---

Assets/Script/UI/InGameUI/FeverUIController.cs

---
about: PR 템플릿
labels: review
assignees: ""
---
Fever SFX 적용

Fever SFX 적용

---

Assets/Script/Managers/DifficultyManager.cs

---
about: PR 템플릿
labels: review
assignees: ""
---

[Docs]난이도 밸런싱 2차안 적용

---

Assets/Script/Managers/DataManager.cs

---
about: PR 템플릿
labels: review
assignees: ""
---
- [Fix] WebGL환경에서도 Sprite Array정렬 순서를 올바르게 받도록 수정
Closes #117

[Fix] WebGL환경에서도 Sprite Array정렬 순서를 올바르게 받도록 수정

---

Assets/featuer_docSO/Document/DocumentController.cs

---
about: PR 템플릿
labels: review
assignees: ""
---
DocumentController.cs 수정

[Fix]터치 딜레이버그 수정

---

Assets/Script/Managers/DataManager.cs

---
about: PR 템플릿
labels: review
assignees: ""
---
- [Fix] Addressables에서 Sprite[] 묶음 캐시 클리어 로직 오류 수정
Closes #132

[Fix] Addressables에서 Sprite[] 묶음 캐시 클리어 로직 오류 수정

---

Assets/Script/Audio/SFXController.cs
Assets/Script/Managers/DifficultyManager.cs
Assets/featuer_docSO/Document/DocumentController.cs

---
about: PR 템플릿
labels: review
assignees: ""
---
DifficultyManager.cs 수정
DocumentController.cs 수정
SFXController.cs 수정 (풀 갯수 20개로 늘림)

[Feat]서류연출시간도DifficultyManager가관리하게수정

---

Assets/Script/Managers/GameStates/InGameState.cs
Assets/Script/Managers/InGameController.cs
Assets/Script/UI/PopupUI/ResultUIController.cs
Assets/Scripts/Classification.cs

- PlayerPrefs의 "BestScore"를 체크하여 게임 플레이 중 최고기록에 도달하면 연출 재생
- 기존 임시 코드 제거
- PlayerPrefs의 "BestScore" 갱신은 결과창에서 진행되도록 (게임 도중에 종료 시 반영되지 않도록)
---
about: PR 템플릿
labels: review
assignees: ""
---
- PlayerPrefs의 "BestScore"를 체크하여 게임 플레이 중 최고기록에 도달하면 연출 재생
- 기존 임시 코드 제거
- PlayerPrefs의 "BestScore" 갱신은 결과창에서 진행되도록 (게임 도중에 종료 시 반영되지 않도록)
Closes #139 

[Feat] InGame NewRecord PlayerPrefs 연동

---

Assets/Scripts/Classification.cs
Assets/featuer_docSO/Document/DocumentController.cs

---
about: PR 템플릿
labels: review
assignees: ""
---
DocumentController.cs 수정
Classification.cs 수정
스프라이트를 바꾸는 로직 자체는 구현하지 않았습니다. 추후 각 반려요소컨트롤러, 장애물컨트롤러 스크립트에서 메서드 형태로 구현해야합니다.

[Wip]분류실패시반려요소및장애물강조표현로직틀구현

---

Assets/featuer_docSO/Document/DocumentPool.cs

---
about: PR 템플릿
labels: review
assignees: ""
---
DocumentPool.cs수정

[Docs]풀이첫생성될때초기크기를받게수정

---

Assets/Script/Managers/AudioManager.cs

- 게임이 백그라운드 상태일 때 음악 Mute
- 다시 포그라운드로 돌아오면 기존 설정에 따라 음악 재생 or Mute
---
about: PR 템플릿
labels: review
assignees: ""
---
- 게임이 백그라운드 상태일 때 음악 Mute
- 다시 포그라운드로 돌아오면 기존 설정에 따라 음악 재생 or Mute
Closes #145 

[Feat] 게임이 백그라운드 상태일 때 음악 Mute

---

Assets/Prefab/UI/PopupUICanvas.prefab
Assets/Script/UI/PopupUI/IntroBackGroundController.cs
Assets/Script/UI/PopupUI/IntroBackGroundController.cs.meta
Assets/Script/UI/PopupUI/IntroUIController.cs

---
about: PR 템플릿
labels: review
assignees: ""
---

인트로 크레딧 해상도 처리

---

Assets/featuer_docSO/Prefabs(test)/obsObj/folder.prefab

---
about: PR 템플릿
labels: review
assignees: ""
---
해당프리팹에 열린서류봉투강조스프라이트적용

[Resource]열린서류봉투강조스프라이트적용

---

Assets/Script/Managers/GameManager.cs
Assets/Script/Managers/InGameController.cs
Assets/Script/UI/PopupUI/PauseUIController.cs
Assets/featuer_docSO/Document/DocumentController.cs

팝업패널이사라지는순간장애물터치가안되야할상태에서터치되던문제수정
---
about: PR 템플릿
labels: review
assignees: ""
---
DocumentController.cs수정
GameManager.cs수정
InGameController.cs수정
PauseUIController.cs수정

[Fix]패널및장애물연동문제수정

---

Assets/Prefab/UI/Popup/ResultUI.prefab
Assets/Script/UI/PopupUI/ResultUIController.cs

- 결과창에서 바로 재시작 할 수 있도록 기능 추가
---
about: PR 템플릿
labels: review
assignees: ""
---
- 결과창에서 바로 재시작 할 수 있도록 기능 추가
Closes #157 

[Feat] 결과창에 재시작 추가

---

Assets/Script/Managers/DifficultyManager.cs

---
about: PR 템플릿
labels: review
assignees: ""
---

[Docs]5차밸런싱수정

---

Assets/Script/UI/InGameUI/ClassificationUIController.cs
Assets/Scripts/Classification.cs

---
about: PR 템플릿
labels: review
assignees: ""
---

[fix]시간증가텍스트가뜨지않는버그수정
